### ISSUE TITLE
直接运行start.bat 报tcp端口的错误

### ISSUE THREAD

**Issue by ht-dep** [ewail/odoo_win10#1]
运行start.bat后，报错
File "D:\CCode\GitCodes\odoo_win10\thirdparty\python\lib\site-packages\psycopg2\__init__.py", line 178, in connect
    return _connect(dsn, connection_factory=connection_factory, async=async)
psycopg2.OperationalError: could not connect to server: Connection refused (0x0000274D/10061)
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused (0x0000274D/10061)
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?

**Comment by ht-dep** [comment]
应该是数据库没启动

**Comment by ht-dep** [comment]
用pg_ctl -D D:\CCode\GitCodes\odoo_win10\pgsql\data -l D:\CCode\GitCodes\odoo_win10\pgsql\logfile.log start这个命令，没有启动数据库

**Comment by ewail** [comment]
这个问题解决了吗？

**Comment by ht-dep** [comment]
解决了，我的电脑  不能运行打包的postgresql

**Comment by ewail** [comment]
好的，你管理员权限运行试试，一般这个数据库启动不起来，可能是端口占用或者是数据库配置错误。我打包的这个默认安装了所有模块，你可以研究研究，总体觉得odoo是个不错的学习资料。

**Comment by ht-dep** [comment]
嗯，在windows布了套、在ubuntu也弄了套、在centos也弄了套；在看它的web框架，跟其他框架差别好大，不是很理解。有时间会多请教

**Comment by ewail** [comment]
共同学习！
